# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.loader = {
    efi.canTouchEfiVariables = true;
    systemd-boot.enable = true;
  };
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3f7a1eb9-aba1-4dbf-b87c-5a99c7f38b3d";
      fsType = "btrfs";
      options = [ "subvol=root/nixos-09-2017" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c1579a69-8ddb-45ed-8879-e94ea6d5c062";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AAFA-A81A";
      fsType = "vfat";
    };

  swapDevices = [ ];

  virtualisation.virtualbox.guest.enable = true;
}
